---
# yamllint disable rule:comments
# yamllint disable rule:line-length

timestamp_directories: false
timestamp_files: false

downloads:
  sftp: 
    - host: localhost
      port: 2222
      username: foo
      password: pass
      key: ""
      path: "/downloads"
      max_age: "168h"

  s3: []

uploads:
  sftp:
    - host: localhost
      port: 2222
      username: foo
      password: pass
      key: ""
      path: "/uploads"
      max_age: "168h"

  s3:
    - endpoint_url: https://localhost:4566
      env_auth: true
      access_key: ""
      access_secret: ""
      region: us-east-1
      key_prefix: /
      bucket: test
  email: []
  #  enabled: true
  #  recipients:
  #    - email: alexandergfoley@gmail.com
  #      name: Compliance
